version: 0.2

phases:
  install:
    commands:
      - n 18.19.0
      
      ## Dependencies
      - npm install --silent --progress-false
      - npm install --silent --progress=false -g serverless@3.38.0-d09dc659
      - npm install --silent --save–dev serverless-stack-output
      
  build:
    commands:
      ## Tests

  post_build:
    commands:
      ## Post build commands

artifacts:
 files:
   - serverless.yml
   - deploy.sh
   - index.js
   - package.json
   - package-lock.json
